"""add tiktok_accel to trend_scores

Revision ID: 5f0b61dc40ef
Revises: dee27c553ae5
Create Date: 2026-02-17 22:17:54.400214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f0b61dc40ef'
down_revision: Union[str, Sequence[str], None] = 'dee27c553ae5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trend_scores', sa.Column('tiktok_accel', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trend_scores', 'tiktok_accel')
    # ### end Alembic commands ###
