"""add_price_low_and_price_high_to_products

Revision ID: dee27c553ae5
Revises: 58e001d6f16a
Create Date: 2026-02-17 17:59:04.865097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dee27c553ae5'
down_revision: Union[str, Sequence[str], None] = '58e001d6f16a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('price_low', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('price_high', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'price_high')
    op.drop_column('products', 'price_low')
    # ### end Alembic commands ###
